# Generated by Django 3.2.7 on 2021-11-05 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='birdth_day',
        ),
        migrations.AddField(
            model_name='myuser',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='birth_day'),
        ),
    ]
